In [ ]:
# import methods
import pandas as pd

In [ ]:
# original data
T = pd.read_csv('Annual_Surface_Temperature_Change.csv')
T

,ObjectId,Country,ISO2,ISO3,Indicator,Unit,Source,CTS_Code,CTS_Name,CTS_Full_Descriptor,...,F2013,F2014,F2015,F2016,F2017,F2018,F2019,F2020,F2021,F2022
0,1,"Afghanistan, Islamic Rep. of",AF,AFG,Temperature change with respect to a baseline ...,Degree Celsius,Food and Agriculture Organization of the Unite...,ECCS,Surface Temperature Change,"Environment, Climate Change, Climate Indicator...",...,1.281,0.456,1.093,1.555,1.540,1.544,0.910,0.498,1.327,2.012
1,2,Albania,AL,ALB,Temperature change with respect to a baseline ...,Degree Celsius,Food and Agriculture Organization of the Unite...,ECCS,Surface Temperature Change,"Environment, Climate Change, Climate Indicator...",...,1.333,1.198,1.569,1.464,1.121,2.028,1.675,1.498,1.536,1.518
2,3,Algeria,DZ,DZA,Temperature change with respect to a baseline ...,Degree Celsius,Food and Agriculture Organization of the Unite...,ECCS,Surface Temperature Change,"Environment, Climate Change, Climate Indicator...",...,1.192,1.690,1.121,1.757,1.512,1.210,1.115,1.926,2.330,1.688
3,4,American Samoa,AS,ASM,Temperature change with respect to a baseline ...,Degree Celsius,Food and Agriculture Organization of the Unite...,ECCS,Surface Temperature Change,"Environment, Climate Change, Climate Indicator...",...,1.257,1.170,1.009,1.539,1.435,1.189,1.539,1.430,1.268,1.256
4,5,"Andorra, Principality of",AD,AND,Temperature change with respect to a baseline ...,Degree Celsius,Food and Agriculture Organization of the Unite...,ECCS,Surface Temperature Change,"Environment, Climate Change, Climate Indicator...",...,0.831,1.946,1.690,1.990,1.925,1.919,1.964,2.562,1.533,3.243
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
220,221,Western Sahara,EH,ESH,Temperature change with respect to a baseline ...,Degree Celsius,Food and Agriculture Organization of the Unite...,ECCS,Surface Temperature Change,"Environment, Climate Change, Climate Indicator...",...,1.423,1.401,1.510,1.732,2.204,0.942,1.477,2.069,1.593,1.970
221,222,World,NaN,WLD,Temperature change with respect to a baseline ...,Degree Celsius,Food and Agriculture Organization of the Unite...,ECCS,Surface Temperature Change,"Environment, Climate Change, Climate Indicator...",...,1.016,1.053,1.412,1.660,1.429,1.290,1.444,1.711,1.447,1.394
222,223,"Yemen, Rep. of",YE,YEM,Temperature change with respect to a baseline ...,Degree Celsius,Food and Agriculture Organization of the Unite...,ECCS,Surface Temperature Change,"Environment, Climate Change, Climate Indicator...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
223,224,Zambia,ZM,ZMB,Temperature change with respect to a baseline ...,Degree Celsius,Food and Agriculture Organization of the Unite...,ECCS,Surface Temperature Change,"Environment, Climate Change, Climate Indicator...",...,0.790,0.917,1.450,1.401,0.105,0.648,0.855,0.891,0.822,0.686
224,225,Zimbabwe,ZW,ZWE,Temperature change with respect to a baseline ...,Degree Celsius,Food and Agriculture Organization of the Unite...,ECCS,Surface Temperature Change,"Environment, Climate Change, Climate Indicator...",...,0.118,0.025,0.970,1.270,0.088,0.453,0.925,0.389,-0.125,-0.490

In [ ]:
# Keep Country and Years 1992-2020 columns
selected_columns = ['Country'] + [f'F{year}' for year in range(1992, 2021)]
T_selected = T[selected_columns]
T_selected

,Country,F1992,F1993,F1994,F1995,F1996,F1997,F1998,F1999,F2000,...,F2011,F2012,F2013,F2014,F2015,F2016,F2017,F2018,F2019,F2020
0,"Afghanistan, Islamic Rep. of",-0.294,0.220,0.430,0.359,-0.116,0.471,0.675,1.198,0.993,...,1.397,0.223,1.281,0.456,1.093,1.555,1.540,1.544,0.910,0.498
1,Albania,0.106,0.076,1.330,-0.172,-0.038,0.075,0.795,0.670,1.065,...,1.055,1.487,1.333,1.198,1.569,1.464,1.121,2.028,1.675,1.498
2,Algeria,-0.312,0.552,0.732,0.595,0.846,1.059,1.109,1.476,0.820,...,1.398,1.147,1.192,1.690,1.121,1.757,1.512,1.210,1.115,1.926
3,American Samoa,0.344,-0.069,0.189,0.755,0.784,NaN,NaN,0.242,0.626,...,0.854,0.924,1.257,1.170,1.009,1.539,1.435,1.189,1.539,1.430
4,"Andorra, Principality of",0.386,0.174,1.508,1.279,0.570,1.788,1.018,1.055,1.050,...,1.677,1.265,0.831,1.946,1.690,1.990,1.925,1.919,1.964,2.562
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
220,Western Sahara,0.529,0.315,0.903,1.356,1.353,1.536,1.415,0.935,0.874,...,1.579,1.344,1.423,1.401,1.510,1.732,2.204,0.942,1.477,2.069
221,World,0.184,0.348,0.507,0.835,0.355,0.656,0.993,0.783,0.728,...,0.921,1.074,1.016,1.053,1.412,1.660,1.429,1.290,1.444,1.711
222,"Yemen, Rep. of",NaN,NaN,NaN,NaN,NaN,0.107,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
223,Zambia,0.544,-0.117,0.362,0.761,0.393,0.339,0.876,0.064,-0.040,...,0.956,0.972,0.790,0.917,1.450,1.401,0.105,0.648,0.855,0.891
224,Zimbabwe,1.010,0.300,-0.085,0.685,-0.247,-0.025,0.801,0.030,-0.417,...,0.232,0.334,0.118,0.025,0.970,1.270,0.088,0.453,0.925,0.389

In [ ]:
# Rename years columns to T[Year]
renamed_columns = {'Country': 'Country'}
for year in range(1992, 2021):
    renamed_columns[f'F{year}'] = f'T{year}'

T_selected = T_selected.rename(columns=renamed_columns)
T_selected

,Country,T1992,T1993,T1994,T1995,T1996,T1997,T1998,T1999,T2000,...,T2011,T2012,T2013,T2014,T2015,T2016,T2017,T2018,T2019,T2020
0,"Afghanistan, Islamic Rep. of",-0.294,0.220,0.430,0.359,-0.116,0.471,0.675,1.198,0.993,...,1.397,0.223,1.281,0.456,1.093,1.555,1.540,1.544,0.910,0.498
1,Albania,0.106,0.076,1.330,-0.172,-0.038,0.075,0.795,0.670,1.065,...,1.055,1.487,1.333,1.198,1.569,1.464,1.121,2.028,1.675,1.498
2,Algeria,-0.312,0.552,0.732,0.595,0.846,1.059,1.109,1.476,0.820,...,1.398,1.147,1.192,1.690,1.121,1.757,1.512,1.210,1.115,1.926
3,American Samoa,0.344,-0.069,0.189,0.755,0.784,NaN,NaN,0.242,0.626,...,0.854,0.924,1.257,1.170,1.009,1.539,1.435,1.189,1.539,1.430
4,"Andorra, Principality of",0.386,0.174,1.508,1.279,0.570,1.788,1.018,1.055,1.050,...,1.677,1.265,0.831,1.946,1.690,1.990,1.925,1.919,1.964,2.562
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
220,Western Sahara,0.529,0.315,0.903,1.356,1.353,1.536,1.415,0.935,0.874,...,1.579,1.344,1.423,1.401,1.510,1.732,2.204,0.942,1.477,2.069
221,World,0.184,0.348,0.507,0.835,0.355,0.656,0.993,0.783,0.728,...,0.921,1.074,1.016,1.053,1.412,1.660,1.429,1.290,1.444,1.711
222,"Yemen, Rep. of",NaN,NaN,NaN,NaN,NaN,0.107,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
223,Zambia,0.544,-0.117,0.362,0.761,0.393,0.339,0.876,0.064,-0.040,...,0.956,0.972,0.790,0.917,1.450,1.401,0.105,0.648,0.855,0.891
224,Zimbabwe,1.010,0.300,-0.085,0.685,-0.247,-0.025,0.801,0.030,-0.417,...,0.232,0.334,0.118,0.025,0.970,1.270,0.088,0.453,0.925,0.389

In [ ]:
# extract to csv file
file_path = "T_preprocessed.csv"
T_selected.to_csv(file_path, index=False)
print(f"T_selected has been saved to {file_path}")

T_selected has been saved to T_preprocessed.csv